/// Data models for the Basirah knowledge base and for the structured answers
/// that both the app and the API produce.
library;

/// How an answer is shaped. Mirrors the response-control rules of the
/// approved reference.
enum AnswerKind {
  /// A documented answer (levels A/B, or a constrained level-C answer).
  answer,

  /// A matter of recognised scholarly difference: state what is agreed upon,
  /// declare the difference, never pick a side.
  khilaf,

  /// A personal case or fatwa request (level D): general information only,
  /// then referral to a qualified person or body.
  refer,

  /// Not enough documented reference to answer with confidence.
  abstain,

  /// Not a question about Islam (restaurants, sport, another religion's
  /// doctrines for their own sake…): politely declined, never answered.
  offTopic;

  static AnswerKind parse(String? value) => AnswerKind.values.firstWhere(
    (k) => k.name == value,
    orElse: () => AnswerKind.abstain,
  );
}

/// Content levels (أ/ب/ج/د) from the reference pack.
enum ContentLevel {
  a('A', 'أ'),
  b('B', 'ب'),
  c('C', 'ج'),
  d('D', 'د');

  const ContentLevel(this.code, this.letterAr);

  final String code;
  final String letterAr;

  static ContentLevel parse(String? value) => ContentLevel.values.firstWhere(
    (l) => l.code == (value ?? '').trim().toUpperCase(),
    orElse: () => ContentLevel.b,
  );
}

/// Where an answer came from.
enum AnswerOrigin {
  /// Curated knowledge-base entry (human-authored, pending/after Sharia review).
  kb,

  /// Generated by the language model, grounded in the closed knowledge base.
  ai,

  /// Produced locally by the deterministic router (no model available).
  offline;

  static AnswerOrigin parse(String? value) => AnswerOrigin.values.firstWhere(
    (o) => o.name == value,
    orElse: () => AnswerOrigin.offline,
  );
}

enum EvidenceKind {
  quran,
  hadith;

  static EvidenceKind parse(String? value) =>
      value == 'hadith' ? EvidenceKind.hadith : EvidenceKind.quran;
}

/// A verbatim Quran verse or hadith from the closed evidence registry.
/// Answers may cite these by id only; they never quote free text.
class Evidence {
  const Evidence({
    required this.id,
    required this.kind,
    required this.text,
    this.surah,
    this.surahName,
    this.ayah,
    this.narrator,
    this.source,
    this.grade,
    this.search,
    this.tafsir,
    this.tafsirSource,
    this.tafsirUrl,
    this.note,
    this.translation,
    this.translationSource,
  });

  final String id;
  final EvidenceKind kind;

  /// The Arabic text, always shown as is.
  final String text;

  /// English meaning (Quran: King Fahd Complex's Hilali–Khan translation;
  /// hadith: team translation of the meaning, pending review).
  final String? translation;
  final String? translationSource;

  /// Verbatim tafsir excerpt shown under a verse (the explanation in
  /// موسوعة التفسير, الدرر السنية).
  final String? tafsir;
  final String? tafsirSource;

  /// Page with the full tafsir the model read (the passage on dorar.net/tafseer).
  final String? tafsirUrl;

  /// Model-written "why this verse is relevant" — labelled as generated.
  final String? note;

  // Quran
  final int? surah;
  final String? surahName;
  final String? ayah;

  // Hadith
  final String? narrator;
  final String? source;
  final String? grade;
  final String? search;

  bool get isQuran => kind == EvidenceKind.quran;

  /// Human-readable citation, e.g. «الممتحنة: 8» or «صحيح البخاري (2620)».
  String get reference =>
      isQuran ? '${surahName ?? ''}: ${ayah ?? ''}' : (source ?? '');

  /// Link to the approved platform where the text can be verified: for a
  /// verse, its own page (the first verse of a range) on the association's
  /// موسوعة المحتوى الإسلامي باللغات, with the Mushaf text and the approved
  /// translation.
  String get url => urlFor('ar');

  String urlFor(String lang) => isQuran
      ? 'https://islamenc.com/${lang == 'en' ? 'en' : 'ar'}/quran/${surah ?? 1}/${_firstAyah ?? 1}'
      : 'https://dorar.net/hadith/search?q=${Uri.encodeQueryComponent(search ?? text)}';

  int? get _firstAyah => int.tryParse((ayah ?? '').split(RegExp('[–-]')).first.trim());

  /// The surah in Dorar's tafsir encyclopedia (dorar.net/tafseer) — the
  /// tafsir platform named by the reference pack.
  String? get dorarTafsirUrl => isQuran && surah != null ? 'https://dorar.net/tafseer/$surah' : null;

  String get platformName => isQuran ? 'موسوعة المحتوى الإسلامي' : 'الدرر السنية';

  String platformNameFor(String lang) =>
      lang == 'en' ? (isQuran ? 'IslamEnc' : 'Dorar.net') : platformName;

  Evidence copyWith({
    String? text,
    String? surahName,
    String? narrator,
    String? source,
    String? grade,
    String? translation,
    String? translationSource,
    String? tafsir,
    String? tafsirSource,
    String? note,
  }) => Evidence(
    id: id,
    kind: kind,
    text: text ?? this.text,
    surah: surah,
    surahName: surahName ?? this.surahName,
    ayah: ayah,
    narrator: narrator ?? this.narrator,
    source: source ?? this.source,
    grade: grade ?? this.grade,
    search: search,
    tafsir: tafsir ?? this.tafsir,
    tafsirSource: tafsirSource ?? this.tafsirSource,
    tafsirUrl: tafsirUrl,
    note: note ?? this.note,
    translation: translation ?? this.translation,
    translationSource: translationSource ?? this.translationSource,
  );

  factory Evidence.fromJson(Map<String, dynamic> j) => Evidence(
    id: j['id'] as String,
    kind: EvidenceKind.parse(j['kind'] as String?),
    text: j['text'] as String,
    surah: j['surah'] as int?,
    surahName: j['surahName'] as String?,
    ayah: j['ayah']?.toString(),
    narrator: j['narrator'] as String?,
    source: j['source'] as String?,
    grade: j['grade'] as String?,
    search: j['search'] as String?,
    tafsir: j['tafsir'] as String?,
    tafsirSource: j['tafsirSource'] as String?,
    tafsirUrl: j['tafsirUrl'] as String?,
    note: j['note'] as String?,
    translation: j['translation'] as String?,
    translationSource: j['translationSource'] as String?,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'kind': kind.name,
    'text': text,
    if (surah != null) 'surah': surah,
    if (surahName != null) 'surahName': surahName,
    if (ayah != null) 'ayah': ayah,
    if (narrator != null) 'narrator': narrator,
    if (source != null) 'source': source,
    if (grade != null) 'grade': grade,
    if (search != null) 'search': search,
    if (tafsir != null) 'tafsir': tafsir,
    if (tafsirSource != null) 'tafsirSource': tafsirSource,
    if (tafsirUrl != null) 'tafsirUrl': tafsirUrl,
    if (note != null) 'note': note,
    if (translation != null) 'translation': translation,
    if (translationSource != null) 'translationSource': translationSource,
  };

  /// Verse keys covered by a Quran item («60:8», or «53:3»,«53:4» for a range).
  List<String> get verseKeys {
    if (!isQuran || surah == null || ayah == null) return const [];
    final parts = ayah!.split(RegExp('[–-]')).map((s) => int.tryParse(s.trim())).toList();
    if (parts.isEmpty || parts.first == null) return const [];
    final from = parts.first!;
    final to = parts.length > 1 && parts[1] != null ? parts[1]! : from;
    return [for (var a = from; a <= to; a++) '$surah:$a'];
  }
}

class Category {
  const Category({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.description,
    required this.hue,
    required this.star,
    required this.icon,
  });

  final String id;
  final String title;
  final String subtitle;
  final String description;

  /// HSL hue (0–360) used to tint the category's cover art.
  final double hue;

  /// Number of points of the cover-art rosette (8, 10, 12, 16…).
  final int star;
  final String icon;

  factory Category.fromJson(Map<String, dynamic> j) => Category(
    id: j['id'] as String,
    title: j['title'] as String,
    subtitle: j['subtitle'] as String,
    description: j['description'] as String,
    hue: (j['hue'] as num).toDouble(),
    star: j['star'] as int,
    icon: j['icon'] as String,
  );
}

/// One curated question with its structured, card-shaped answer.
class FaqEntry {
  const FaqEntry({
    required this.id,
    required this.categoryId,
    required this.question,
    required this.variants,
    required this.tags,
    required this.level,
    required this.kind,
    required this.principle,
    required this.culture,
    required this.guidance,
    required this.khilafAgreed,
    required this.khilafNote,
    required this.referReason,
    required this.referTo,
    required this.evidenceIds,
    required this.review,
    required this.popular,
  });

  final String id;
  final String categoryId;
  final String question;
  final List<String> variants;
  final List<String> tags;
  final ContentLevel level;
  final AnswerKind kind;
  final String principle;
  final String culture;
  final List<String> guidance;
  final String khilafAgreed;
  final String khilafNote;
  final String referReason;
  final String referTo;
  final List<String> evidenceIds;

  /// `pending` until a qualified Sharia reviewer signs the entry off.
  final String review;
  final bool popular;

  factory FaqEntry.fromJson(Map<String, dynamic> j) => FaqEntry(
    id: j['id'] as String,
    categoryId: j['category'] as String,
    question: j['question'] as String,
    variants: _strings(j['variants']),
    tags: _strings(j['tags']),
    level: ContentLevel.parse(j['level'] as String?),
    kind: AnswerKind.parse(j['kind'] as String?),
    principle: (j['principle'] as String?) ?? '',
    culture: (j['culture'] as String?) ?? '',
    guidance: _strings(j['guidance']),
    khilafAgreed: (j['khilafAgreed'] as String?) ?? '',
    khilafNote: (j['khilafNote'] as String?) ?? '',
    referReason: (j['referReason'] as String?) ?? '',
    referTo: (j['referTo'] as String?) ?? '',
    evidenceIds: _strings(j['evidence']),
    review: (j['review'] as String?) ?? 'pending',
    popular: (j['popular'] as bool?) ?? false,
  );
}

class GlossaryTerm {
  const GlossaryTerm({
    required this.term,
    required this.english,
    required this.rule,
    required this.keys,
  });

  final String term;
  final String english;
  final String rule;

  /// Extra lookup keys (Arabic and Latin spellings).
  final List<String> keys;

  factory GlossaryTerm.fromJson(Map<String, dynamic> j) => GlossaryTerm(
    term: j['term'] as String,
    english: j['english'] as String,
    rule: j['rule'] as String,
    keys: _strings(j['keys']),
  );
}

class SourceLink {
  const SourceLink(this.label, this.url);
  final String label;
  final String url;
}

/// One row of «المرجعية العلمية المعتمدة».
class ApprovedSource {
  const ApprovedSource({
    required this.field,
    required this.content,
    required this.rule,
    required this.links,
  });

  final String field;
  final String content;
  final String rule;
  final List<SourceLink> links;

  factory ApprovedSource.fromJson(Map<String, dynamic> j) => ApprovedSource(
    field: j['field'] as String,
    content: j['content'] as String,
    rule: j['rule'] as String,
    links: [
      for (final l in (j['links'] as List? ?? const []))
        SourceLink(
          (l as Map<String, dynamic>)['label'] as String,
          l['url'] as String,
        ),
    ],
  );
}

/// One row of «مستويات المحتوى وضبط الاستجابة».
class LevelPolicy {
  const LevelPolicy({
    required this.level,
    required this.title,
    required this.scope,
    required this.handling,
  });

  final ContentLevel level;
  final String title;
  final String scope;
  final String handling;

  factory LevelPolicy.fromJson(Map<String, dynamic> j) => LevelPolicy(
    level: ContentLevel.parse(j['level'] as String?),
    title: j['title'] as String,
    scope: j['scope'] as String,
    handling: j['handling'] as String,
  );
}

/// One item of «المعيار العلمي الملزم لمخرجات الحلول» and how Basirah applies it.
class Standard {
  const Standard({
    required this.title,
    required this.text,
    required this.applied,
  });

  final String title;
  final String text;
  final String applied;

  factory Standard.fromJson(Map<String, dynamic> j) => Standard(
    title: j['title'] as String,
    text: j['text'] as String,
    applied: j['applied'] as String,
  );
}

/// A platform named in the reference pack (pp. 8–15), verbatim.
class ApprovedPlatform {
  const ApprovedPlatform({
    required this.section,
    required this.name,
    required this.content,
    required this.links,
    this.basirahUse,
    this.mcp = false,
  });

  final String section;
  final String name;
  final List<String> content;
  final List<SourceLink> links;

  /// How Basirah uses it (Basirah's note, not the pack's), when it does.
  final String? basirahUse;

  /// Served by the association's MCP server for AI models.
  final bool mcp;

  factory ApprovedPlatform.fromJson(Map<String, dynamic> j) => ApprovedPlatform(
    section: j['section'] as String,
    name: j['name'] as String,
    content: _strings(j['content']),
    links: [
      for (final l in (j['links'] as List? ?? const []))
        SourceLink((l as Map<String, dynamic>)['label'] as String, l['url'] as String),
    ],
    basirahUse: j['basirahUse'] as String?,
    mcp: (j['mcp'] as bool?) ?? false,
  );
}

/// The reference pack's texts beyond the tables: the scope, the
/// association's statement (p. 8) and the notes on external platforms.
class PackTexts {
  const PackTexts({
    this.scope = const [],
    this.standardsIntro = '',
    this.associationName = '',
    this.associationAbout = '',
    this.associationFacts = const [],
    this.associationMcp = '',
    this.externalIntro = '',
    this.externalNote = '',
  });

  final List<String> scope;
  final String standardsIntro;
  final String associationName;
  final String associationAbout;
  final List<(String, String)> associationFacts;
  final String associationMcp;
  final String externalIntro;
  final String externalNote;

  factory PackTexts.fromJson(Map<String, dynamic> j) {
    final a = (j['association'] as Map?)?.cast<String, dynamic>() ?? const {};
    return PackTexts(
      scope: _strings(j['scopeText']),
      standardsIntro: (j['standardsIntro'] as String?) ?? '',
      associationName: (a['name'] as String?) ?? '',
      associationAbout: (a['about'] as String?) ?? '',
      associationFacts: [
        for (final f in (a['facts'] as List? ?? const []))
          ((f as Map)['item'] as String, f['text'] as String),
      ],
      associationMcp: (a['mcp'] as String?) ?? '',
      externalIntro: (j['externalIntro'] as String?) ?? '',
      externalNote: (j['externalNote'] as String?) ?? '',
    );
  }
}

/// The whole curated corpus. Loaded from `assets/kb/*.json` by the app and
/// from the same files by the API, so both always reason over one source.
class KnowledgeBase {
  KnowledgeBase({
    required this.version,
    required this.categories,
    required this.entries,
    required this.evidence,
    required this.glossary,
    required this.sources,
    required this.levels,
    required this.standards,
    this.platforms = const [],
    this.pack = const PackTexts(),
    this.lang = 'ar',
    Map<String, dynamic>? english,
  }) : _english = english,
       _entriesById = {for (final e in entries) e.id: e},
       _categoriesById = {for (final c in categories) c.id: c};

  /// Language of the texts: 'ar' (the master text) or 'en' (after [localized]).
  final String lang;

  /// Raw English overlay (`assets/kb/en.json`), if loaded.
  final Map<String, dynamic>? _english;

  bool get hasEnglish => _english != null;

  final String version;
  final List<Category> categories;
  final List<FaqEntry> entries;
  final Map<String, Evidence> evidence;
  final List<GlossaryTerm> glossary;
  final List<ApprovedSource> sources;
  final List<LevelPolicy> levels;
  final List<Standard> standards;

  /// The platforms of the reference pack (pp. 8–15), Arabic, verbatim.
  final List<ApprovedPlatform> platforms;
  final PackTexts pack;

  final Map<String, FaqEntry> _entriesById;
  final Map<String, Category> _categoriesById;

  FaqEntry? entry(String id) => _entriesById[id];
  Category? category(String id) => _categoriesById[id];

  List<FaqEntry> entriesIn(String categoryId) =>
      entries.where((e) => e.categoryId == categoryId).toList();

  List<FaqEntry> get popular => entries.where((e) => e.popular).toList();

  /// Resolves evidence ids, silently skipping anything not in the registry.
  List<Evidence> resolveEvidence(Iterable<String> ids) => [
    for (final id in ids)
      if (evidence[id] != null) evidence[id]!,
  ];

  LevelPolicy? policyFor(ContentLevel level) {
    for (final p in levels) {
      if (p.level == level) return p;
    }
    return null;
  }

  static const quranTranslationSource =
      'The Noble Quran — translation of the meanings by al-Hilali & Khan (King Fahd Complex)';
  static const hadithTranslationSource =
      'Translation of the meaning — Basirah team, pending review';

  /// The same knowledge base with English texts (Arabic Quran and hadith
  /// text are kept; their English meaning is added). Arabic questions stay
  /// searchable as variants, so either language finds the same entry.
  KnowledgeBase localized(String target) {
    final en = _english;
    if (target != 'en' || en == null || lang == 'en') return this;
    Map<String, dynamic> section(String name) =>
        (en[name] as Map?)?.cast<String, dynamic>() ?? const {};
    Map<String, dynamic>? item(String name, String id) =>
        (section(name)[id] as Map?)?.cast<String, dynamic>();
    String pick(Map<String, dynamic>? m, String key, String fallback) {
      final v = m?[key];
      return v is String && v.trim().isNotEmpty ? v : fallback;
    }

    List<T> list<T>(String name, List<T> base, T Function(T b, Map<String, dynamic> m) apply) {
      final rows = (en[name] as List?) ?? const [];
      return [
        for (var i = 0; i < base.length; i++)
          i < rows.length && rows[i] is Map ? apply(base[i], (rows[i] as Map).cast<String, dynamic>()) : base[i],
      ];
    }

    return KnowledgeBase(
      lang: 'en',
      english: en,
      version: version,
      platforms: platforms,
      pack: pack,
      categories: [
        for (final c in categories)
          () {
            final m = item('categories', c.id);
            return Category(
              id: c.id,
              title: pick(m, 'title', c.title),
              subtitle: pick(m, 'subtitle', c.subtitle),
              description: pick(m, 'description', c.description),
              hue: c.hue,
              star: c.star,
              icon: c.icon,
            );
          }(),
      ],
      entries: [
        for (final e in entries)
          () {
            final m = item('entries', e.id);
            final guidance = m?['guidance'] is List ? _strings(m!['guidance']) : e.guidance;
            return FaqEntry(
              id: e.id,
              categoryId: e.categoryId,
              question: pick(m, 'question', e.question),
              variants: [...e.variants, e.question],
              tags: e.tags,
              level: e.level,
              kind: e.kind,
              principle: pick(m, 'principle', e.principle),
              culture: pick(m, 'culture', e.culture),
              guidance: guidance,
              khilafAgreed: pick(m, 'khilafAgreed', e.khilafAgreed),
              khilafNote: pick(m, 'khilafNote', e.khilafNote),
              referReason: pick(m, 'referReason', e.referReason),
              referTo: pick(m, 'referTo', e.referTo),
              evidenceIds: e.evidenceIds,
              review: e.review,
              popular: e.popular,
            );
          }(),
      ],
      evidence: {
        for (final ev in evidence.values)
          ev.id: () {
            if (ev.isQuran) {
              final m = item('quran', ev.id);
              return ev.copyWith(
                text: m?['arabic'] as String?,
                surahName: pick(m, 'surahName', ev.surahName ?? ''),
                translation: m?['translation'] as String?,
                translationSource: m?['translation'] == null ? null : quranTranslationSource,
              );
            }
            final m = item('hadith', ev.id);
            return ev.copyWith(
              narrator: pick(m, 'narrator', ev.narrator ?? ''),
              source: pick(m, 'source', ev.source ?? ''),
              grade: pick(m, 'grade', ev.grade ?? ''),
              translation: m?['text'] as String?,
              translationSource: m?['text'] == null ? null : hadithTranslationSource,
            );
          }(),
      },
      glossary: [
        for (final g in glossary)
          GlossaryTerm(
            term: g.term,
            english: g.english,
            rule: pick({'rule': section('glossary')[g.term]}, 'rule', g.rule),
            keys: g.keys,
          ),
      ],
      sources: list(
        'sources',
        sources,
        (b, m) => ApprovedSource(
          field: pick(m, 'field', b.field),
          content: pick(m, 'content', b.content),
          rule: pick(m, 'rule', b.rule),
          links: b.links,
        ),
      ),
      levels: [
        for (final l in levels)
          () {
            final m = item('levels', l.level.code);
            return LevelPolicy(
              level: l.level,
              title: pick(m, 'title', l.title),
              scope: pick(m, 'scope', l.scope),
              handling: pick(m, 'handling', l.handling),
            );
          }(),
      ],
      standards: list(
        'standards',
        standards,
        (b, m) => Standard(
          title: pick(m, 'title', b.title),
          text: pick(m, 'text', b.text),
          applied: pick(m, 'applied', b.applied),
        ),
      ),
    );
  }

  /// Ids of items that have no English text yet (for tests and reviewers).
  List<String> missingEnglish() {
    final en = _english;
    if (en == null) return const ['<no en.json>'];
    bool has(String section, String id, List<String> keys) {
      final m = (en[section] as Map?)?[id];
      return m is Map && keys.every((k) => m[k] != null && m[k].toString().trim().isNotEmpty);
    }

    return [
      for (final c in categories)
        if (!has('categories', c.id, const ['title', 'subtitle', 'description'])) 'category:${c.id}',
      for (final e in entries)
        if (!has('entries', e.id, [
          'question',
          'guidance',
          if (e.principle.isNotEmpty) 'principle',
          if (e.culture.isNotEmpty) 'culture',
          if (e.khilafAgreed.isNotEmpty) 'khilafAgreed',
          if (e.khilafNote.isNotEmpty) 'khilafNote',
          if (e.referReason.isNotEmpty) 'referReason',
          if (e.referTo.isNotEmpty) 'referTo',
        ]))
          'entry:${e.id}',
      for (final ev in evidence.values)
        if (ev.isQuran && !has('quran', ev.id, const ['surahName', 'translation'])) 'quran:${ev.id}',
      for (final ev in evidence.values)
        if (!ev.isQuran && !has('hadith', ev.id, const ['narrator', 'text', 'source', 'grade'])) 'hadith:${ev.id}',
      for (final g in glossary)
        if (((en['glossary'] as Map?)?[g.term] ?? '').toString().trim().isEmpty) 'glossary:${g.term}',
      for (final l in levels)
        if (!has('levels', l.level.code, const ['title', 'scope', 'handling'])) 'level:${l.level.code}',
      if (((en['sources'] as List?) ?? const []).length != sources.length) 'sources',
      if (((en['standards'] as List?) ?? const []).length != standards.length) 'standards',
    ];
  }

  factory KnowledgeBase.fromJsonFiles({
    required Map<String, dynamic> categories,
    required Map<String, dynamic> faqs,
    required Map<String, dynamic> evidence,
    required Map<String, dynamic> reference,
    Map<String, dynamic>? english,
  }) {
    final ev = [
      for (final e in evidence['evidence'] as List)
        Evidence.fromJson(e as Map<String, dynamic>),
    ];
    return KnowledgeBase(
      english: english,
      version: (faqs['version'] as String?) ?? '0',
      categories: [
        for (final c in categories['categories'] as List)
          Category.fromJson(c as Map<String, dynamic>),
      ],
      entries: [
        for (final e in faqs['entries'] as List)
          FaqEntry.fromJson(e as Map<String, dynamic>),
      ],
      evidence: {for (final e in ev) e.id: e},
      glossary: [
        for (final g in reference['glossary'] as List)
          GlossaryTerm.fromJson(g as Map<String, dynamic>),
      ],
      sources: [
        for (final s in reference['sources'] as List)
          ApprovedSource.fromJson(s as Map<String, dynamic>),
      ],
      levels: [
        for (final l in reference['levels'] as List)
          LevelPolicy.fromJson(l as Map<String, dynamic>),
      ],
      standards: [
        for (final s in reference['standards'] as List)
          Standard.fromJson(s as Map<String, dynamic>),
      ],
      platforms: [
        for (final p in (reference['platforms'] as List? ?? const []))
          ApprovedPlatform.fromJson(p as Map<String, dynamic>),
      ],
      pack: PackTexts.fromJson(reference),
    );
  }
}

/// A structured answer, rendered by the app as colour-coded cards.
/// Produced from a curated entry, by the model, or by the offline router.
class BasirahAnswer {
  const BasirahAnswer({
    required this.question,
    required this.kind,
    required this.level,
    required this.origin,
    this.principle = '',
    this.culture = '',
    this.guidance = const [],
    this.khilafAgreed = '',
    this.khilafNote = '',
    this.referReason = '',
    this.referTo = '',
    this.abstainReason = '',
    this.evidence = const [],
    this.sourceNote = '',
    this.entryId,
    this.related = const [],
    this.review = 'pending',
    this.model,
    this.research = const [],
    this.guard = const [],
  });

  /// How the answer was researched, e.g. «بحث: …», «قراءة تفسير: الممتحنة ٨».
  final List<String> research;

  /// What the guard did to a live answer before it was shown (e.g. «dropped
  /// 60:8: cited without reading its tafsir»), for «إيصال بصيرة».
  final List<String> guard;

  final String question;
  final AnswerKind kind;
  final ContentLevel level;
  final AnswerOrigin origin;
  final String principle;
  final String culture;
  final List<String> guidance;
  final String khilafAgreed;
  final String khilafNote;
  final String referReason;
  final String referTo;
  final String abstainReason;
  final List<Evidence> evidence;

  /// Non-verse sources such as the approved glossary.
  final String sourceNote;

  /// The curated entry this answer comes from or is closest to.
  final String? entryId;

  /// Ids of related curated entries to suggest next.
  final List<String> related;
  final String review;
  final String? model;

  /// Stable key used for bookmarks.
  String get key => entryId != null && origin == AnswerOrigin.kb
      ? 'kb:$entryId'
      : 'q:${question.trim()}';

  factory BasirahAnswer.fromEntry(
    FaqEntry e,
    KnowledgeBase kb, {
    AnswerOrigin origin = AnswerOrigin.kb,
    String? question,
    List<String> related = const [],
    List<String> extraGuidance = const [],
  }) => BasirahAnswer(
    question: question ?? e.question,
    kind: e.kind,
    level: e.level,
    origin: origin,
    principle: e.principle,
    culture: e.culture,
    guidance: [...e.guidance, ...extraGuidance],
    khilafAgreed: e.khilafAgreed,
    khilafNote: e.khilafNote,
    referReason: e.referReason,
    referTo: e.referTo,
    // A referral (the question needs a specialist) cites nothing.
    evidence: e.kind == AnswerKind.refer ? const [] : kb.resolveEvidence(e.evidenceIds),
    entryId: e.id,
    related: related,
    review: e.review,
  );

  BasirahAnswer copyWith({
    String? question,
    List<String>? related,
    List<String>? guidance,
    List<String>? guard,
  }) => BasirahAnswer(
    question: question ?? this.question,
    kind: kind,
    level: level,
    origin: origin,
    principle: principle,
    culture: culture,
    guidance: guidance ?? this.guidance,
    khilafAgreed: khilafAgreed,
    khilafNote: khilafNote,
    referReason: referReason,
    referTo: referTo,
    abstainReason: abstainReason,
    evidence: evidence,
    sourceNote: sourceNote,
    entryId: entryId,
    related: related ?? this.related,
    review: review,
    model: model,
    research: research,
    guard: guard ?? this.guard,
  );

  factory BasirahAnswer.fromJson(Map<String, dynamic> j) => BasirahAnswer(
    question: (j['question'] as String?) ?? '',
    kind: AnswerKind.parse(j['kind'] as String?),
    level: ContentLevel.parse(j['level'] as String?),
    origin: AnswerOrigin.parse(j['origin'] as String?),
    principle: (j['principle'] as String?) ?? '',
    culture: (j['culture'] as String?) ?? '',
    guidance: _strings(j['guidance']),
    khilafAgreed: (j['khilafAgreed'] as String?) ?? '',
    khilafNote: (j['khilafNote'] as String?) ?? '',
    referReason: (j['referReason'] as String?) ?? '',
    referTo: (j['referTo'] as String?) ?? '',
    abstainReason: (j['abstainReason'] as String?) ?? '',
    evidence: [
      for (final e in (j['evidence'] as List? ?? const []))
        Evidence.fromJson(e as Map<String, dynamic>),
    ],
    sourceNote: (j['sourceNote'] as String?) ?? '',
    entryId: j['entryId'] as String?,
    related: _strings(j['related']),
    review: (j['review'] as String?) ?? 'pending',
    model: j['model'] as String?,
    research: _strings(j['research']),
    guard: _strings(j['guard']),
  );

  Map<String, dynamic> toJson() => {
    'question': question,
    'kind': kind.name,
    'level': level.code,
    'origin': origin.name,
    'principle': principle,
    'culture': culture,
    'guidance': guidance,
    'khilafAgreed': khilafAgreed,
    'khilafNote': khilafNote,
    'referReason': referReason,
    'referTo': referTo,
    'abstainReason': abstainReason,
    'evidence': [for (final e in evidence) e.toJson()],
    'sourceNote': sourceNote,
    'entryId': entryId,
    'related': related,
    'review': review,
    'model': model,
    'research': research,
    if (guard.isNotEmpty) 'guard': guard,
  };
}

List<String> _strings(Object? v) =>
    v is List ? [for (final x in v) x.toString()] : const [];
